### ISSUE TITLE
Different colors for LOG | INFO | WARN | ERROR

### ISSUE THREAD

**Issue by StevenBlack** [starak/node-console-stamp#15]
Idly wondering if it's possible to optionally display different colors by type of console call, like red for error, yellowish for warning, blue for info.

Would this be a doable enhancement?  

Thanks for considering it!

**Comment by starak** [comment]
Do you mean the whole thing or just the labels?

**Comment by StevenBlack** [comment]
The whole string of console output.  The stamp, the type, and the message string based on the console method called.

Or alternately, the color of the stamp, the type, or the message stating, but based on the console method called.

My use case is, full screen of console output, typically scrolling with time, and distinguishing at a glance which are errors, and which are info, as opposed to which are just console.log.

**Comment by danielcha** [comment]
Yes, I came here looking for this feature!

**Comment by the-AjK** [comment]
+1

**Comment by starak** [comment]
Ok. I couldn't find a good way to do this, so I made a new branch and a new npm module for you :) Take look at [console-stripe](https://www.npmjs.com/package/console-stripe) @StevenBlack @danielcha @the-AjK

**Comment by StevenBlack** [comment]
This is cool Ståle @starak!  Thank you!

**Comment by progmem64** [comment]
You can pass a function to `options.colors.*` (e.g. `options.colors.labels`). You can then apply custom styling.

My solution for colored labels (tested @ v0.2.6):
```javascript
const chalk = require('chalk');

function labelColorizer(options) {
    return (inp) => {
        const label = inp.slice(options.labelPrefix.length, -options.labelSuffix.length).toLowerCase();
        return typeof options.colorFuncs[label] === 'function' ? options.colorFuncs[label](inp) : inp;
    };
}

require('console-stamp')(console, {
    pattern: 'dd/mm/yyyy HH:MM:ss.l',
    colors: {
        label: labelColorizer({
            labelPrefix: "[",
            labelSuffix: "]",
            colorFuncs: {
                log: chalk.blue,
                dir: chalk.blue,
                info: chalk.green,
                warn: chalk.yellow,
                assert: chalk.magenta,
                error: chalk.red,
            }
        })
    },
});
```

outputs:
![screenshot 2018-09-27 at 20 56 38](https://user-images.githubusercontent.com/18649298/46168124-e0131f80-c297-11e8-98bb-e120bb9a4bb1.png)
