### ISSUE TITLE
Allow for the disabling of certain logging levels.

### ISSUE THREAD

**Issue by SteffanDonal** [starak/node-console-stamp#17]
I'd love to use this library for controlling how much logging is actually output. Is it possible to add an option similar to `include` that allows you to disable functions?  

If not, I'll make another package that does the same style patching, but for that to work and to maintain compatibility with your implementation I'd need the patched indicator's name to change to include the name of this package or something similar - so they can be double-patched and then unpatched.

**Comment by SteffanDonal** [comment]
Happy to make a pull request for either of these options!

**Comment by starak** [comment]
Feel free to make a pull request, @SteffanDonal. This sounds like a good idé!

**Comment by SteffanDonal** [comment]
Pull request created, see: #18

**Comment by starak** [comment]
I'm having trouble with your commit, @SteffanDonal. When i run the ´test.js´ everything is disabled by default. Am I missing something here?

**Comment by starak** [comment]
Need to rewrite this, so reopen

**Comment by SteffanDonal** [comment]
Got it! Sorry about that. PR: #20

**Comment by starak** [comment]
Ok! This is now merged and released :)
