### ISSUE TITLE
Custom stdout / stderr

### ISSUE THREAD

**Issue by NiklasGollenstede** [starak/node-console-stamp#21]
The fact that you pass in a `console` object somewhat implies that you can use this module without messing with any global stuff, however, it always uses `process.stdout` and `process.stderr` and not the streams the `console` object actually uses.

It should ether use the consols own streams or (if it is not possible to get those streams) it should provide options to set them explicitly.

Thanks for your consideration!

**Comment by starak** [comment]
This is by design and therefore not an issue.

As far as I know `console.log()` calls `process.stdout.write` with formatted output and such.

**Comment by NiklasGollenstede** [comment]
You can create custom console instances: https://nodejs.org/api/console.html#console_new_console_stdout_stderr

What's the point in accepting a `console` parameter, if you simply use global behaviour anyway? Why not grab the global console directly?

Not using the global console, but then using the global out/err streams is inconsequent.

**Comment by starak** [comment]
Ah! Now I see what you mean, @NiklasGollenstede. I'll look into it...

**Comment by NiklasGollenstede** [comment]
Pretty much what I had in mind :)

One note though: 
changing
```
process.stdout.write( prefix );
```
to
```
stdout.write( prefix );
```
is a breaking change.

As it happens, it would actually break my workaround for the previously missing option.
something like 

```
var stdout = options.stdout;
...
(stdout || process.stdout).write( prefix );
```
would be much less likely to break anything.

**Comment by starak** [comment]
I have that in a separat line above like this: 

```
    var stdout = options.stdout || process.stdout;
    var stderr = options.stderr || options.stdout || process.stderr;
```
That is much the same, or what? Am I missing something?

**Comment by NiklasGollenstede** [comment]
I know. The difference is that if you previously changed the `stdout` property of the `process` global, `console-stamp` would use the new pipes.
Now it keeps using the once that were there upon the creation of the wrapped console.

**Comment by starak** [comment]
Ah! Ok, good point.

**Comment by starak** [comment]
@NiklasGollenstede: v0.2.4 is now released
