### ISSUE TITLE
bug when extending console-stamp

### ISSUE THREAD

**Issue by lefebvresam** [starak/node-console-stamp#25]
When I define:

```
require('console-stamp')(console, {
 pattern:"dd/mm/yyyy HH:MM:ss.l",
 extend:{debug:5},
 include:["debug", "info", "warn", "error"],
 level:"debug"
});
```

and use it somewhere:

`console.debug('startvalue ' + s.format('HH:mm:ss,SSS') + ' is valid');`

I get:

> [12/02/2017 22:06:13.938] [DEBUG] /home/pi/escape/node_modules/console-stamp/main.js:153
>             return org.apply( con, args );
>                       ^
> 
> TypeError: Cannot read property 'apply' of undefined
>     at Console.con.(anonymous function) [as debug] (/home/pi/escape/node_modules/console-stamp/main.js:153:23)
>     at generatefile (/home/pi/escape/countdowngenerator.js:82:25)
>     at /home/pi/escape/countdowngenerator.js:48:7
>     at /home/pi/escape/countdowngenerator.js:68:11
>     at ChildProcess.exithandler (child_process.js:202:7)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:192:7)
>     at maybeClose (internal/child_process.js:890:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

I use version:

> pi@raspberrypi:~/escape $ npm -v console-stamp
> 4.1.2

> pi@raspberrypi:~/escape $ node -v
> v7.5.0

**Comment by starak** [comment]
I guess you have not added the debug method to the `console` before patching it. Can that be the reason, @lefebvresam ?

**Comment by lefebvresam** [comment]
Can you explain me how to do?

**Comment by starak** [comment]
Sure!
First you have to add your method to the console object, something like this:
```
console.debug = function debug(){
    console.log.apply(console,arguments);
}
```
Then you can add your code after this.

The `extend` and `include` params is just to tell `console-stamp` that you have extended your console with the method.

**Comment by starak** [comment]
So this works for me:
```
console.debug = function debug(){
    console.log.apply(console, arguments);
}
require('console-stamp')(console, {
 pattern:"dd/mm/yyyy HH:MM:ss.l",
 extend:{debug:5},
 include:["debug", "info", "warn", "error"],
 level:"debug"
});
console.debug("Hello, %s","World");
```

**Comment by lefebvresam** [comment]
What is the difference with:

```
console.debug = function(msg) {
    console.log(msg);
}
```

**Comment by starak** [comment]
The main difference is that your debug method only takes one single parameter, while the one i have in this example, send all the parameters and by that gives `debug` the same features as `log`.

But did you all ready have that in your code ?

**Comment by lefebvresam** [comment]
Yes now I have:

```
/// console logging

//var loglevel = 'debug';
var loglevel = 'info';

var cons = require('console-stamp');

console.debug = function debug(){
    console.log.apply(console, arguments);
}

console.fatal = function fatal(){
    console.log.apply(console, arguments);
    process.exit(1);
}

function setloglevel(loglevel) {
 cons(console, {
  pattern:"dd/mm/yyyy HH:MM:ss.l",
  extend:{debug:5},
  include:["debug", "info", "warn", "error"],
  level:loglevel
 });
 console.debug('countdowngenerator: log level put on %s', loglevel);
}
```

and to propagate the log level in case of using as module:

```
if(!module.parent) {
 if (process.argv.length == 4) {
  var videofile = process.argv[2];
  var startvalue = process.argv[3];
  countdowngenerator(videofile, startvalue, loglevel, function(err, result){
   if (err) console.fatal(err.message);
   else console.info(result);
  });
 } else {
  showhelp();
  console.fatal('wrong number of arguments');
 }
} else module.exports = countdowngenerator;
```

with:

```
function countdowngenerator(videofile, startvalue, loglevel, callback) { // (err, result)
 setloglevel(loglevel);
...
```

**Comment by starak** [comment]
Ok! Does it work or do you still get the error?

**Comment by lefebvresam** [comment]
Yes it works perfect. I think it's also a good practice to propagate the log level by a variable in all modules you 'require'. Otherwise when using different log levels at different modules that you also plan to use as a separate command line tool next to modules, the global log level depends on the latest console-stamp being configured. Because of the event driven model in node, this should invoke an undefined behavior.

**Comment by starak** [comment]
Good! 
You can consider using [Custom Console](https://github.com/starak/node-console-stamp#custom-console-v024) if you want to avoid global conflicts with `console`.

Closing this...

**Comment by starak** [comment]
An example with Custom Console:
```
var logger = new console.Console(process.stdout, process.stderr);

logger.debug = function debug() {
    logger.log.apply(logger, arguments);
};

logger.fatal = function debug() {
    logger.log.apply(logger, arguments);
    process.exit(1);
};

console_stamp(logger, {
    pattern: "dd/mm/yyyy HH:MM:ss.l",
    extend: {debug: 5, fatal:1},
    include: ["debug", "fatal", "info", "warn", "error"],
    level: "debug"
});

logger.debug("debug");
logger.fatal("fatal");
```
