### ISSUE TITLE
get timestamp in IST

### ISSUE THREAD

**Issue by shreyawhiz** [starak/node-console-stamp#26]
So using this module with default settings gives me time in UTC.
How can i change and get it in IST format?

**Comment by starak** [comment]
The default setting uses the server timezome, so you can fix this by changing the server.

However, you can use the Moment Timezone NPM module in combination with the `custom formatter` to manipulate the timezone like this:

First install the `moment-timezone` module to your project:
```
$ npm i moment-timezone --save
```
then, in your script:

```javascript
const moment = require('moment-timezone').tz('Asia/Kolkata'); // <-- IST

require( "console-stamp" )( console, {
    formatter: function(){
        return moment().format("LLLL");
    }
} );
``` 

For more information on the costom formatter look here: https://github.com/starak/node-console-stamp#custom-formatter-example

**Comment by starak** [comment]
@shreyawhiz Note that I'm on vacation and have not tried this out, so there can be some typos or whatever...
