### ISSUE TITLE
[node v10] assert output broken (assert internally calls warn?!)

### ISSUE THREAD

**Issue by progmem64** [starak/node-console-stamp#29]
I have a problem regarding the assert method. 

I am using node v10 and according to the docs (https://nodejs.org/api/console.html#console_console_assert_value_message) the implementation of assert did change with v10.0.0.

The following code:
```javascript
require('console-stamp')(console, { pattern: 'dd/mm/yyyy HH:MM:ss.l' });
console.assert(false, "test");
```

outputs:
```
[27/09/2018 20:34:15.680] [ASSERT][27/09/2018 20:34:15.687] [WARN]  Assertion failed: test
```

whereas expected is something like:

```
[27/09/2018 20:34:15.680] [ASSERT] Assertion failed: test
``` 

Seems like assert internally calls the warn method.

**Comment by starak** [comment]
Thanks, @progmem64 !
I'll look into it
