### ISSUE TITLE
DST

### ISSUE THREAD

**Issue by roughnecks** [starak/node-console-stamp#31]
Hello.

I'm in Italy (CET) and we currently have daylight saving, so it's UTC+2. but console-stamps seems to be ignoring that and shows time as UTC+1.

Sorry if this issue is not related to console-stamp, would appreciate if you can redirect me to the proper place.

Thanks

**Comment by starak** [comment]
Console-stamp by default uses what ever the server/computer is set to. 
However, you can look at my answer in #26 if you want to change it in javascript.

**Comment by roughnecks** [comment]
Well, my PC is set to Italy Timezone and this is what I get from a terminal where my code is running:

zenlab@ZENITH:~$ date
gio 25 apr 2019, 23.05.51, DST

But console stamp says that:

[22:02:31] [LOG]
[22:02:31] [LOG]    ZED version: v2.1.3
[22:02:31] [LOG]    node.js version: v10.15.3

**Comment by starak** [comment]
And what if you just `console.log(new Date())` in node.js ?

**Comment by roughnecks** [comment]
[22:33:11] [LOG]    2019-04-25T21:33:11.277Z

**Comment by starak** [comment]
Hmm. Ok. I'll look in to it...

**Comment by starak** [comment]
Ok, the issue is in the [dateformat](https://github.com/felixge/node-dateformat) dependency. Not much activity on that package lately.

I am working on a [new major release](https://github.com/starak/node-console-stamp/tree/3.0.0), and I will try to handle this issue there.

**Comment by starak** [comment]
But strangly enough, I'm in the same timezone (Norway) and does not have this issue.

starak@eir:~/tmp $ date
Fri Apr 26 00:09:19 CEST 2019

require('console-stamp')(console)
console.log('hepp')
[Fri Apr 26 2019 00:10:52] [LOG]    hepp

**Comment by roughnecks** [comment]
I checked again and in fact when I issued the date command it returned "DST", not sure why.
So I ran:
sudo dpkg-reconfigure tzdata
and selected Rome and now it's fine.

zenlab@ZENITH:~$ date
ven 26 apr 2019, 00.19.48, CEST

Sorry for the troubles.

**Comment by roughnecks** [comment]
Just for the records, it's WSL, not a "real" linux install.
