### ISSUE TITLE
custom file output (Custom Console)

### ISSUE THREAD

**Issue by bannostookaylo** [starak/node-console-stamp#33]
For whatever reason I am just not getting this where is console_stamp defined?

```
require('console-stamp')(console, {
    colors: {
        stamp: 'yellow',
        label: 'white',
        metadata: 'green'
    }
});

const output = fs.createWriteStream(`./logs/stdout.${getLogFileDate()}.log`);
const errorOutput = fs.createWriteStream(`./logs/stderr.${getLogFileDate()}.log`);
const logger = new console.Console(output, errorOutput);

console_stamp(logger, {
    stdout: output,
    stderr: errorOutput
});
```

I thought it might be from `const console_stamp = require('console-stamp')` but that proved to be incorrect. I keep getting the error ```TypeError: console_stamp is not a function```

**Comment by bannostookaylo** [comment]
I changed it to

```require('console-stamp')( logger, {```

it seems to not be giving me that error. However, I don't see anything writing to the output files. The files were made but nothing is being logged to them.

**Comment by bannostookaylo** [comment]
Just tried 

```
    console_stamp( console, {
        stdout: output,
        stderr: errorOutput
    } );
```

and it kinda worked... finally output to my file but it was only the timestamp and the label no message

**Comment by bannostookaylo** [comment]
I'd really like to use this extension so if I could please get some help on how to properly implement "Custom Console" that would be awesome thanks :)

**Comment by bannostookaylo** [comment]
I just ran 

```
npm install console-stamp@next
```
incase maybe something for this has been fixed

**Comment by bannostookaylo** [comment]
Hmmm yea looks like updating to v3 didn't work either

```
/**
 * Logging stuff
 */
require('console-stamp')(console);

const output = fs.createWriteStream(`./logs/stdout.${getLogFileDate()}.log`);
const errorOutput = fs.createWriteStream(`./logs/stderr.${getLogFileDate()}.log`);
const logger = new console.Console(output, errorOutput);

require('console-stamp')(logger, {
    stdout: output,
    stderr: errorOutput
});

// end logging stuff

console.log( ' LOG ' );
console.error( ' ERROR ' );
```

**Comment by bannostookaylo** [comment]
just ran this test 

```
const output = fs.createWriteStream(`./logs/stdout.${getLogFileDate()}.log`);

output.write('foop\n');
output.write('bop\n');
return;
```
and foo bop wrote to the file

**Comment by bannostookaylo** [comment]
if i rearrange some code in `index.js` then i get some output although its not formatted very nicely

```
    include.forEach( method => {
        const stream = selectOutputStream(method, config);
        const trg = con[method];

                    stream.write( `${generatePrefix(method, config)} ` );

        con[method] = new Proxy( trg, {
            apply: ( target, context, arguments ) => {
                if ( checkLogLevel( config, method ) ) {
                    //stream.write( `${generatePrefix(method, config)} ` );
                    target.apply( context, arguments );
                }
            }
        } );

        con.__patched = true
    } );
```

as far as i can tell the `stream` var is getting changed somehow within the new Proxy part

**Comment by bannostookaylo** [comment]
```    const config = generateConfig( options );

console.debug( config );

    const include = config.include.filter(m => typeof con[m] === 'function');

    const org = {};
    Object.keys(con).forEach(m => org[m] = con[m]);
    con.org = org;

    include.forEach( method => {
        const stream = selectOutputStream(method, config);
        const trg = con[method];

        con[method] = new Proxy( trg, {
            apply: ( target, context, arguments ) => {
                if ( checkLogLevel( config, method ) ) {

console.debug( config );
                    stream.write( `${generatePrefix(method, config)} ` );
                    target.apply( context, arguments );
                }
            }
        } );

        con.__patched = true
    } );```

the outputs for config.stdout are different in this as well

**Comment by bannostookaylo** [comment]
interesting I just ran 
```
    include.forEach( method => {
        const stream = config.stdout; //selectOutputStream(method, config);
        const trg = con[method];

console.debug( method );
console.debug( stream.path );

        con[method] = new Proxy( trg, {
            apply: ( target, context, arguments ) => {
                if ( checkLogLevel( config, method ) ) {
                    stream.write( `${generatePrefix(method, config)} ` );
                    target.apply( context, arguments );
                }
            }
        } );

        con.__patched = true
    } );
```
and the output was 
```
log
undefined
debug
./logs/stdout.20190611.log
log
./logs/stdout.20190611.log
info
./logs/stdout.20190611.log
warn
./logs/stdout.20190611.log
error
./logs/stdout.20190611.log
```
for whatever reason log is `undefined`

**Comment by bannostookaylo** [comment]
yea im running up against brick walls trying to figure this out....

**Comment by bannostookaylo** [comment]
switching back to the older version of console-stamp

**Comment by bannostookaylo** [comment]
made a stackoverflow for this as well... just documenting in case others go down this path https://stackoverflow.com/questions/56547226/cant-get-console-stamp-to-log-to-custom-output-file

**Comment by bannostookaylo** [comment]
tried going just this and it worked

```
const logger = new console.Console(output, errorOutput);

logger.log( " TEST LOGGER " );
```

**Comment by starak** [comment]
Thank you for your feedback!

I think you are mixing up several of the examples in the readme.

First you need to define `console_stamp` if you want to call it like you did in the first post here.  Ex:

```javascript
const console_stamp = require('console-stamp');

const output = fs.createWriteStream(`./logs/stdout.${getLogFileDate()}.log`);
const errorOutput = fs.createWriteStream(`./logs/stderr.${getLogFileDate()}.log`);
const logger = new console.Console(output, errorOutput);

console_stamp(logger, {
    stdout: output,
    stderr: errorOutput
});

logger.log('log msg');
```

`require('console-stamp')(console)` is just an example to patch the global console with default settings, so if you want a custom console you should do as above and then you need to use your custom console, and not the global console, and it will write to your files:
```
logger.log('LOG');
logger.error('ERROR')
```

The @next (3.0.0) version has breaking changes and has it's own README here (WIP): https://github.com/starak/node-console-stamp/tree/3.0.0

**Comment by starak** [comment]
And, Sorry, but i don't have enough points (!) to answer you on stackoverflow :|

**Comment by bannostookaylo** [comment]
LOL its all good I know you dont get paid for this so I figured I may ask there to in case someone has sometime and may know... I will try what you just suggested and let you know what happens... Thank you for the response and this awesome extension.

**Comment by bannostookaylo** [comment]
ooo thatts probably something else I missed was the 
```
logger.log
``` 
part i was still trying to use

```
console.log
```

**Comment by starak** [comment]
Managed to answer your stackoverflow anyway, so nvm. Have a look there :)

**Comment by bannostookaylo** [comment]
Just wanted to share this so that I can log to both console and logger but with only one call in case anyone else runs across this thread

```
// simply logs to both console AND logger
const superlog = new Proxy(new Object(), {
    get(target, method ) {
        return ( message ) => {
            console[method]( message );
            logger[method]( message );
        }
    }
});

superlog.log( ` TEST LOG `);
```

**Comment by bannostookaylo** [comment]
Just gonna put this here in case anyone else stumbles across this thread and finds it useful... made this simple method to log to both console and logger

```
const superlog = new Proxy(new Object(), {
    get(target, method ) {
        return ( message ) => {
            console[method]( message );
            logger[method]( message );
        }
    }
});
```

**Comment by bannostookaylo** [comment]
Only issue i've really ran into with this `superlog` thing I made is that if another module calls `console.log|error|warn|etc...` then that doesn't get logged. Would be cool if this module could some how have this `superlog` type feature available internally so that EVERYTHING could possibly get logged to the custom output file. Anyway just a thought, thank you! :) I'll try to stop flooding your threads now lol
