### ISSUE TITLE
Color Options

### ISSUE THREAD

**Issue by bannostookaylo** [starak/node-console-stamp#34]
Is there a way to color code the "label" based on if its a log or error etc..?

```
[Mon Jun 10 2019 19:41:18] [LOG]
[Mon Jun 10 2019 19:41:18] [ERROR]
```

It would be cool to see "ERROR" in red so it stands out from all the "LOG"s

**Comment by starak** [comment]
It will be possible in version 3.0.0.
I'll come back and give you an example...

**Comment by bannostookaylo** [comment]
Now that I seem to have a handle on your extension I'll go ahead and put version 3.x back on

**Comment by starak** [comment]
Let me see.

In Console-stamp 3.0.0 you can write your own `tokens`, and use them in your `format`. Here is an example, `my_label`, that make use of the default label token, but wraps the result in a `chalk template` if it is the error method.
```javascript
const console_stamp = require( 'console-stamp' );
const chalk = require( "chalk" );

console_stamp( console, {
    format: ':date().yellow :my_label(7).blue',
    tokens: {
        my_label: ( arg ) => {
            const { method, defaultTokens } = arg;
            let label = defaultTokens.label( arg );
            if ( method === 'error' ) {
                label = chalk`{red ${label}}`;
            }
            return label;
        }
    }
} );
```
I set the default label color to blue here, like this `my_label(7).blue`, just to show you that it will override this color.

So, in 3.0 you can prefix your console with whatever you want. Just make a `token` and put it in `format`, starting with a colon, like this:
```javascript
...
console_stamp( console, {
    format: ':my_token(param_1, param_2)',
    tokens: {
        my_token: ( {params: [p1, p2]} ) => {
            // p1 is now 'param_1' and p2 is now 'param_2'
            return '-> Hello, World! -> ';
        }
    }
} );

console.log("Foo")
//-> Hello, World! -> Foo
``` 
(I guess this is a good start for the README for 3.0.0 :)

I hope this helps.

**Comment by bannostookaylo** [comment]
Kill i knew it had something to do with those tokens just couldn't figure out how to apply the `chalk` ... thank you! :)
