### ISSUE TITLE
Logs errors inside "log"

### ISSUE THREAD

**Issue by manolan1** [starak/node-console-stamp#42]
When I use console-stamp (v2) with `console.error` in Node.js 12.16.2, I get the error logged inside a "log" entry:

`[... timestamp ...]  LOG     [... timestamp ...]  ERROR`   etc

I assume this is because `console.error` is using `console.log` internally, but there must be a way round this because the documentation doesn't look like this. So what am I doing wrong?

**Comment by starak** [comment]
Hmm. Can you show me the code? I'm not able to reproduce this issue.
