### ISSUE TITLE
Not work on debug mode

### ISSUE THREAD

**Issue by hosseinpro** [starak/node-console-stamp#43]
I tried this:
`require("console-stamp")(console);`
It works when I run the node program from the command line, but does not work when I run the program from the VSCode debugger. In debug mode the console prints the regular message without a timestamp.

**Comment by starak** [comment]
Thank you for reporting this!
It seems like VSCode hijacks the console in debug mode. There's not much we can do about it, I'm afraid.

**Comment by yoshigev** [comment]
If anyone stumbles over this, this can be solved by adding the following line to `launch.json`:

  ```json
  "outputCapture": "std"
  ```
