### ISSUE TITLE
console.table

### ISSUE THREAD

**Issue by eurohost** [starak/node-console-stamp#45]
When you try to print to console in a new line, for example table, it adds some spaces in front of log

For example when printing a table is more obvious 

![image](https://user-images.githubusercontent.com/35386475/97123500-cb363e00-1734-11eb-8ef0-0adb0cedf242.png)

Try to add an suffix \n or \r\n .. none worked

**Comment by starak** [comment]
Thank you for reporting, @eurohost!
The problem here is that **table** is calling **log** to write the content.
I will try to find a solution here, but can not promise anything for version 2.9

**Comment by starak** [comment]
Fixed in 3.0.0-rc4.3
