### ISSUE TITLE
not working in cosole log

### ISSUE THREAD

**Issue by DreamCatcherJ** [starak/node-console-stamp#47]
customConsole.log.apply( context, arguments );
stream.write( `${generatePrefix( method, config, customConsoleStream.last_msg )} ` );
------------------------------------------------------------------------------------------------------------
in index.js,I think in line 32  is wrong because  the arguments should inclue generatePrefix(xxx)....

just like this: 
let prefix = `${generatePrefix( method, config, customConsoleStream.last_msg )} `
arguments.unshift(prefix)
customConsole.log.apply( context, arguments );

i just fix it with these code .

**Comment by starak** [comment]
I'm not following you here. Can you please give an example of the problem and how to reproduce it?
