### ISSUE TITLE
default export ts

### ISSUE THREAD

**Issue by simllll** [starak/node-console-stamp#49]
the type says there is a default export, but runtime doesn't say so.

`import console_stamp from 'console-stamp';
`(without esModuleInterop)

results into runtime error:
`TypeError: console_stamp_1.default is not a function
`

I guess either the default export is missing, or the types sohould be fixed?

Thanks a lot!

**Comment by starak** [comment]
Ah! Thank you for reporting! I'll add the default export and patch it asap...

**Comment by simllll** [comment]
Thanks for this quick fix :)
