### ISSUE TITLE
Using in conjunction with a logger that creates separate out.log and err.log files

### ISSUE THREAD

**Issue by ejbaker** [starak/node-console-stamp#5]
Full disclosure: the logger in question is what comes with a node-windows package that creates a Windows service.

I know. I'm sorry, too. I occasionally think fondly of when I originally set this up on an Ubuntu server...

But anyway, that piece of middleware creates separate log files based on protocol -- error and log. And unfortunately, when I use console-stamp, the timestamp portion winds up in the wrong log file.

.out.log:
```
[14:09:55.404] Test
[14:09:55.404] [14:09:55.419] Express server listening on port xxxx in development mode.
```

.err.log:
```
Test 2
```

Obviously that middle timestamp should be in the error log.

A quick glance at the source code tells me the issue is that process.stdout is being used to write timestamps; a check to use process.stderr in the event of console.error calls would fix it.

**Comment by starak** [comment]
Ok, interesting! I'll look into it. Thanks @ejbaker

**Comment by ejbaker** [comment]
NP. For my particular use case, "warn" should also use the process.stderr, and I think that probably also makes sense generally. The others were all fine in log. (Though "assert" didn't wind up in either log file, an oversight on the part of the other module writer.)

**Comment by starak** [comment]
@ejbaker Can you try out my latest commit?
You can install it directly from github like this:

    $ npm install starak/node-console-stamp

I've tested it successfully by running the *test.js* like this:

    $ node test.js 2>> error.log 1>> output.log

**Comment by ejbaker** [comment]
Windows threw up on that command, but I did manually copy the files into the correct places. (main.js, package.json just for fun.) And it seems to work now!
