### ISSUE TITLE
Console Logging Not Working

### ISSUE THREAD

**Issue by QC-Development** [starak/node-console-stamp#50]
I tried to use this but it does not work. Nothing inside the file stdout.log and stderr.log

`
require('console-stamp')(console, { 
    format: ':date(yyyy/mm/dd HH:MM:ss.l) :label' 
} );

const fs = require('fs');
const output = fs.createWriteStream('./stdout.log');
const errorOutput = fs.createWriteStream('./stderr.log');
const logger = new console.Console(output, errorOutput);

require('console-stamp')(logger, {
    stdout: output,
    stderr: errorOutput
});

console.log("Sad Life")
console.info("Sad Life")
console.warn("Sad Life")
console.debug("Sad Life")
console.error("Sad Life")
`

**Comment by starak** [comment]
Try logger.log("Happy Life") and that will be written to your stdout.log

**Comment by starak** [comment]
If you want your global console to write to files you can do a combination of what you have done, like this: 
```javascript
const fs = require('fs');
const output = fs.createWriteStream('./stdout.log');
const errorOutput = fs.createWriteStream('./stderr.log');

require('console-stamp')(console, {
    format: ':date(yyyy/mm/dd HH:MM:ss.l) :label',
    stdout: output,
    stderr: errorOutput
});
```
