### ISSUE TITLE
Correct usage with workers?

### ISSUE THREAD

**Issue by ericman314** [starak/node-console-stamp#55]
What is the correct way to use this with workers? When I use both `console.log` and `console.error` (or `console.warn`) inside a worker, the output appears to be all over the place:

```
[2021/07/27 12:57:37.738] [LOG] [2021/07/27 12:57:37.739] [ERROR] Log 1 from worker
[2021/07/27 12:57:37.740] [LOG] Log 2 from worker
Error 1 from worker
[2021/07/27 12:57:37.740] [ERROR] Error 2 from worker
```

## test-parent.js ##
```js
const { Worker } = require('worker_threads')
const worker = new Worker('./test-worker.js')
```

## test-worker.js ##
```js
require('console-stamp')(console, { format: ':date(yyyy/mm/dd HH:MM:ss.l) :label' })
console.log('Log 1 from worker')
console.error('Error 1 from worker')
console.log('Log 2 from worker')
console.error('Error 2 from worker')
```

I'm using Ubuntu 20.04 and node v14.15.4. Thanks!

**Comment by starak** [comment]
Thank you for reporting, @ericman314 !
I'm able to reproduce, but have clue why this is happening. I guess it's some kind of race condition / async issue here. I'll look in to it...
