### ISSUE TITLE
Chalk Style error

### ISSUE THREAD

**Issue by chriskinsman** [starak/node-console-stamp#62]
Trying to log out a string that includes a filename and am getting:
```
deploy/node_modules/console-stamp/node_modules/chalk/source/templates.js:90
			throw new Error(`Unknown Chalk style: ${styleName}`);
			^

Error: Unknown Chalk style: csv
    at buildStyle 
```

A simple repro case to produce the above:

```
console.log('Test (1).csv');
```

Looks like chalk is picking up the (1) and trying to interpret the .csv that follows as a style.  

Is there any way to disable the chalk styling?

**Comment by starak** [comment]
@chriskinsman Hmm. I can not reproduce issue out of the box. The following example works fine on the latest version:
```javascript
require('console-stamp')(console);
console.log('Test (1).csv');
```

Can you provide some more details? Setup/config, OS and version (node and connsole-stamp)?

**Comment by chriskinsman** [comment]
Interesting.  

Node v16.16.0
Console-Stamp: 3.0.6

We set it up like this:

```
const logger = new console.Console(process.stdout);
const console_stamp = require('console-stamp');
const moment = require('moment');
const chalk = require('chalk');

const map = {
    log: 'cyanBright',
    error: 'red',
    info: 'blue',
    warn: 'yellow',
};

module.exports = function () {
    console_stamp(logger, {
        format: ':timestamp() :label :msg',
        tokens: {
            timestamp: () => {
                return `${moment().local().utcOffset(-7).format()}`;
            },
            label: (obj) => {
                return chalk`{${map[obj.method] || 'reset'} ${obj.method}}:`;
            },
        },
        include: ['debug', 'log', 'info', 'warn', 'error', 'trace'],
    });
    return logger;
};
```

Then call it as:

```
logger.info('Test (1).csv');
```

**Comment by JoA-MoS** [comment]
To add some context I stepped through the console-stamp code and it is in the generatePrefix -> color groups section where it fails -  https://github.com/starak/node-console-stamp/blob/master/lib/utils.js#L63

With the logger and string @chriskinsman provided it calls chalk with `decorator = 'csv'` and `ret = '1'`

**Comment by JoA-MoS** [comment]
We have it solved by removing :msg from the format string. 

We will also update the format to use :label:labelFormat where labelFormat just returns the `.blue` style chalk format utils

**Comment by starak** [comment]
Ah! Now i understand what's happening here. I'll have a look at it...
