### ISSUE TITLE
Replace chalk by ansis?

### ISSUE THREAD

**Issue by KristjanESPERANTO** [starak/node-console-stamp#67]
I played a bit with colored messages and since I also still have CommonJS projects, and the latest version of chalk no longer supports CommonJS, it was not possible (without using an old chalk version) in the way that was used in your [example](https://github.com/starak/node-console-stamp/blob/main/examples/colored-message/index.js).

I then solved it with [ansis](https://github.com/webdiscus/ansis#compare). Wouldn't that also be a good replacement for this project? ansis has a few other advantages besides CommonJS support - check out this [comparison](https://github.com/webdiscus/ansis#compare).

I could understand if you reject this, as it would probably a breaking change.

**Comment by starak** [comment]
Hi @KristjanESPERANTO 
Thank you for bringing this to my attention and for your valuable input. I appreciate the time you've taken to explore alternatives and understand your concerns regarding the compatibility of chalk with CommonJS projects.

However, for the "console-stamp" project, I'm planning a transition to TypeScript in the near future. Given this roadmap and the existing integration with chalk, I've decided to continue using chalk for the time being. This decision is based on a few considerations:

1. **Consistency**: Staying with chalk maintains consistency in the codebase, which is especially important during the transition to TypeScript.
2. **Stability**: chalk has been a stable and reliable dependency for this project, and I'd prefer to minimize the number of major changes during the TypeScript rewrite.
3. **Community Support**: chalk is widely used and well-supported in the community, which is beneficial for long-term maintenance and support.

That said, I'm always open to revisiting this decision in the future, especially post the TypeScript migration.

Again, thank you for your suggestion!

**Comment by KristjanESPERANTO** [comment]
Hi @starak! 🙂

Thank you for your clear and insightful answer!

Do you already know if you are dropping CommonJS support through the migration? If you continue to support CommonJS, I am optimistic to find a way for me to use node-console-stamp with ansis instead of chalk. I'll be happy to share my findings with you.

Thank you very much for maintaining this module for over 10 years now! 👏
