### ISSUE TITLE
Way to ommit LOG/INFO/ERROR/etc..

### ISSUE THREAD

**Issue by simakwm** [starak/node-console-stamp#7]
Is there a way to ommit those prefixes from log?

**Comment by starak** [comment]
This will be possible in the next release.

**Comment by starak** [comment]
@simakwm Feel free to test out the release candidate by installing directly from github like this:

    $ npm install https://github.com/starak/node-console-stamp.git

To omit the labels, you turn them off like this:

    require("console-stamp")(console,{pattern:"...",label:false});
