### ISSUE TITLE
Specify Date along with timestamp

### ISSUE THREAD

**Issue by anvk** [starak/node-console-stamp#9]
Is it even possible using your module ?

**Comment by starak** [comment]
@anvk : Not sure I'm following. Can you give an example of your wanted output?

**Comment by anvk** [comment]
[22/06/2015 20:04:05.969] [LOG] LOG

Adding a datestamp to the log along with time.

**Comment by starak** [comment]
Ah! Of course! :)

    require("console-stamp")(console, "dd/mm/yyyy HH:MM:ss.l");

or anything else supported by [dateFormat](https://github.com/felixge/node-dateformat)

**Comment by anvk** [comment]
Thank you. It would be very helpful for developers if this could be mentioned in README and in the description of NPM package.

**Comment by starak** [comment]
Ack! Thank you for the feedback, @anvk
